import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Notes App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundColor:'black'}}>
     
        <div className="max-w-3xl mx-auto p-4 " style={{ position: 'relative', zIndex: 100 }}>
        <Navbar/>
       
       
        {children}
        </div>
        </body>
    </html>
  )
}
